_config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("users.urls")),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
	path('', views.HomeView.as_view(), name='home'),
	path('users/register/', views.RegisterView.as_view(), name='register'),
	path('users/login/', views.LoginView.as_view(), name='login'),
	path('users/logout/', views.LogoutView.as_view(), name='logout'),
	path('users/profile/', views.ProfileView.as_view(), name='profile'),
	path('users/ideas/', views.IdeasView.as_view(), name='ideas'),
	path('users/tests/', views.TestsView.as_view(), name='tests'),
]

templates/_base.html
{% load static %}

<!doctype html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" type="image/png" href="{% static 'python.png' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
            crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/eb885aa743.js" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>

<style>
    {#Removes this annoying asterisk symbol (*) added by cripsy-forms#}
    .asteriskField {
        display: none;
    }
</style>

{% block navigation %}{% include "_navigation.html" %}{% endblock navigation %}

<section>
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="card shadow-lg" style="border-radius: 1.5rem">
                <div class="card-body p-4 text-center">
                    {% block content %}{% endblock content %}
                </div>
            </div>
        </div>
    </div>
</section>

{% include "_messages.html" %}

<script>
    let allInputs = [...document.querySelectorAll("input")]
    let validInputs = allInputs.filter(item => item.type !== 'hidden')
    validInputs.length && validInputs[0].focus()
</script>

</body>
</html>

templates/_messages.html
{% if messages %}

    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show timed-message
            position-absolute start-50 top-50 translate-middle w-50 text-center" role="alert" style="opacity:0.8">
            <strong>{{ message }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}

    <script>
        setTimeout(function () {
            document.querySelector(".timed-message").remove()
        }, 3000);
    </script>

{% endif %}

templates/_navigation.html
<nav class="navbar navbar-expand-md shadow">
    <div class="container w-75">
        <span class="mx-3">Current user:</span>
        {% if user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'users:profile' %}">
                {{ user }}
                {% if user.subscribed %}
                    <i class="fa-solid fa-check"></i>
                {% else %}
                    <i class="fa-solid fa-xmark"></i>
                {% endif %}
            </a>
        {% else %}
            <a class="navbar-brand" href="{% url 'users:home' %}">Guest</a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="d-flex justify-content-end">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'users:home' %}">Home</a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'users:profile' %}">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'users:ideas' %}">Ideas</a>
                        </li>
                        <li class="nav-item me-4">
                            <a class="nav-link" aria-current="page" href="{% url 'users:tests' %}">Tests</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'users:tests' %}">Tests</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</nav>


templates/test_template.html
{% extends '_base.html' %}

{% block title %}Testing{% endblock title %}

{% block content %}
    {% load crispy_forms_tags %}
    <h2>Automatic tests</h2>
    <form method="post" id="testing_form">
        {% csrf_token %}
        <button class="btn btn-success mx-1 w-50 shadow" type="submit">Run Tests!</button>
    </form>

{% endblock content %}
